#+STARTUP: showall
#+OPTIONS: toc:nil
#+title: JAIF -- Appel à contributions

* Appel à contributions

Pour proposer une présentation de vos travaux, il suffit d'envoyer
avant le TODO-DEADLINE [[mailto:jaif@saxifrage.saclay.cea.fr?subject=CfP: ][un mail au comité d'organisation]] précisant :

 - un résumé de votre présentation (de 15 lignes à une page max. au format libre),
 - l’orateur pressenti,
 - la langue de présentation (français ou anglais). Les présentations
   peuvent être faites en français ou en anglais, de préférence en
   présentiel, ou à distance.

Les propositions seront sélectionnées sur la base d'un équilibre entre
les thématiques couvertes, les travaux préliminaires et les résultats
aboutis.

*** Dates importantes

+ Deadline pour l’envoi de résumé : à préciser
+ Réponse aux auteurs             : à préciser
+ JAIF                            : 7 Novembre 2022

******** TODO update dates
:PROPERTIES:
:TRIGGER:  chain-find-next(TODO,todo-only,from-current,no-wrap)
:CREATED:  [2022-05-05 jeu. 11:10]
:END:
