#+STARTUP: showall
#+OPTIONS: toc:nil
#+title: JAIF

** Lieu

Amphithéâtre D030 - Grenoble INP Esisar
50 rue Barthélémy de Laffemas BP 54
26902 Valence Cedex 9

Plan d'accès :  [[file:media/Esisar - PLAN.pdf][Comment venir à l'Esisar]]

Coordonnées GPS
- Latitude 44.917059°
- Longitude 4.915496°

L'accueil café à partir de 9h se fera dans la salle C004.

** Navettes gare TGV -- Esisar
:PROPERTIES:
:CUSTOM_ID: navettes
:END:

Une navette sera spécialement affrétée pour les participants de JAIF,
entre la gare TGV de Valence et l'Esisar (temps de trajet 10 min.).

Sous réserve que les horaires des trains ne soient pas modifiés :

- Le *matin*, deux départs de la gare TGV: *8h30*,  *9h40*,
  pour les voyageurs dans les TGV de Paris (Direct 2h10) : 6h14-8h14 et 7h14-9h24
- L'*après-midi*, trois départs de l'Esisar: *16h00*, *17h00*, et *18h20*,
  pour les voyageurs dans les TGV vers Paris : 16h35-18h46, 17h35-19h48, et 18h49-21h12.

*** Accès aux navettes affrétées pour JAIF

- *Aller* :: À la gare Valence TGV, sortir par la porte "Alpes" puis se rendre à la station de bus (100 m environ). Environ 12 min de trajet.
- *Retour* :: Les navettes pour la gare TGV partiront de la rue Barthélémy de Laffemas (rue devant l'Esisar).

** Accès en transports en commun
:PROPERTIES:
:CUSTOM_ID: tc
:END:

1. Depuis la gare TGV, prendre un bus "IC intercitéa" direction "Valence gare routière" et s’arrêter à "Pôle bus" (puis voir ci-dessous). Environ 14 min de trajet.
2. A la gare Valence ville, il faut sortir de la gare et aller au "Pôle bus" (6 minutes à pied environ). Puis, prendre le "bus 20" direction "Montélier centre", et s’arrêter à l'arrêt "Valence Pôle Briffaut" OU prendre le bus "Cité 2" vers "Valence Pôle Briffaut" et s'arréter à l'arrêt "IUT". Environ 14 min de trajet.


** Hotels
:PROPERTIES:
:CUSTOM_ID: hotels
:END:

- Le plus proche de l'Esisar et du Social Event : [[https://valence-sud.campanile.com][Campanile Valence sud]]
- En centre ville, en face de la gare.  Le service de bus s'arrête à
  20h, l'accès au centre-ville nécessite donc un taxi en soirée.
  - [[https://www.hotel-les-negociants.com][Les négociants]]
  - [[https://www.hotel-de-lyon.fr/][Hotel de Lyon]]

** Social Event
:PROPERTIES:
:CUSTOM_ID: socialevent
:END:

La soirée aura lieu au [[https://www.theplace2beer-cave.com][place 2 beer]], un bar à bières et vins, avec de belles planches de charcuterie et fromage, en face de l'Esisar.
